# Generated by Django 2.0 on 2018-08-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180813_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=1, max_digits=19),
            preserve_default=False,
        ),
    ]
