# Generated by Django 2.0 on 2018-08-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20180829_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='service',
        ),
    ]
