# Generated by Django 2.0 on 2018-09-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='poostcode',
            new_name='postcode',
        ),
    ]
